/// <reference types="react-native-css/types" />

import "react-native";
 
// NOTE: This file should not be edited and should be committed with your source code. It is generated by react-native-css. If you need to move or disable this file, please see the documentation.

// Fallback augmentation for workspace/bundler setups where TypeScript does not
// apply the package's exported declaration merge to react-native primitives.
declare module "react-native" {
  interface ViewProps {
    className?: string;
    cssInterop?: boolean;
  }

  interface TextProps {
    className?: string;
    cssInterop?: boolean;
  }

  interface ImagePropsBase {
    className?: string;
    cssInterop?: boolean;
  }

  interface ScrollViewProps {
    contentContainerClassName?: string;
    indicatorClassName?: string;
  }

  interface TextInputProps {
    placeholderClassName?: string;
  }
}
