import type {
  AdminDashboardSummary,
  AgentPerformance,
  BranchDashboardSummary,
  LoanDetailSummary,
  MemberProfile,
  TransactionRequest,
} from "./domain";

export const branchPerformance: BranchDashboardSummary["agentPerformance"] = [
  {
    id: "agt-amina",
    name: "Amina",
    collectionsToday: 120000,
    pendingApprovals: 4,
    cashVariance: -2000,
  },
  {
    id: "agt-paul",
    name: "Paul",
    collectionsToday: 80000,
    pendingApprovals: 2,
    cashVariance: 0,
  },
  {
    id: "agt-rita",
    name: "Rita",
    collectionsToday: 65000,
    pendingApprovals: 1,
    cashVariance: 0,
  },
];

export const adminDashboard: AdminDashboardSummary = {
  branchCount: 3,
  totalMembers: 4280,
  totalAgents: 54,
  totalSavings: 45200000,
  totalDeposits: 12700000,
  totalLoans: 31400000,
  outstandingPrincipal: 18900000,
  interestCollected: 3200000,
  overdueLoans: 143,
  pendingApprovals: 54,
  cashVariance: 300000,
  branchPerformance: [
    {
      id: "br-bamenda",
      name: "Bamenda Central",
      managerName: "Rose M.",
      memberCount: 642,
      agentCount: 18,
      totalSavings: 8200000,
      totalDeposits: 2400000,
      totalLoans: 5100000,
      outstandingPrincipal: 3000000,
      pendingApprovals: 12,
      cashVariance: -2000,
    },
    {
      id: "br-douala",
      name: "Douala North",
      managerName: "Peter T.",
      memberCount: 901,
      agentCount: 25,
      totalSavings: 10100000,
      totalDeposits: 3000000,
      totalLoans: 7300000,
      outstandingPrincipal: 4100000,
      pendingApprovals: 18,
      cashVariance: 0,
    },
    {
      id: "br-buea",
      name: "Buea Main",
      managerName: "Linda A.",
      memberCount: 388,
      agentCount: 11,
      totalSavings: 4600000,
      totalDeposits: 1800000,
      totalLoans: 2900000,
      outstandingPrincipal: 1700000,
      pendingApprovals: 7,
      cashVariance: 0,
    },
  ],
};

export const branchDashboard: BranchDashboardSummary = {
  branchId: "br-bamenda",
  branchName: "Bamenda Central",
  totalMembers: 642,
  activeAgents: 18,
  newMembersThisMonth: 24,
  totalSavings: 8200000,
  totalDeposits: 2400000,
  totalLoans: 5100000,
  outstandingPrincipal: 3000000,
  interestCollected: 420000,
  overdueLoans: 18,
  pendingApprovals: 12,
  expectedCashToday: 145000,
  cashVariance: -2000,
  agentPerformance: branchPerformance,
};

export const members: MemberProfile[] = [
  {
    id: "mbr-00124",
    branchId: "br-bamenda",
    branchName: "Bamenda Central",
    agentId: "agt-amina",
    agentName: "Amina",
    fullName: "John Nkem",
    phone: "+237600000001",
    status: "active",
    occupation: "Trader",
    address: "Mile 4 Nkwen",
  },
  {
    id: "mbr-00125",
    branchId: "br-bamenda",
    branchName: "Bamenda Central",
    agentId: "agt-amina",
    agentName: "Amina",
    fullName: "Marie T.",
    phone: "+237600000002",
    status: "active",
    occupation: "Farmer",
    address: "Up Station",
  },
];

export const transactions: TransactionRequest[] = [
  {
    id: "txn-00045",
    memberId: "mbr-00124",
    memberName: "John Nkem",
    branchId: "br-bamenda",
    branchName: "Bamenda Central",
    agentId: "agt-amina",
    agentName: "Amina",
    type: "deposit",
    accountType: "savings",
    amount: 5000,
    status: "pending_approval",
    createdAt: "2026-03-27T08:53:00Z",
  },
  {
    id: "txn-00041",
    memberId: "mbr-00124",
    memberName: "John Nkem",
    branchId: "br-bamenda",
    branchName: "Bamenda Central",
    agentId: "agt-amina",
    agentName: "Amina",
    type: "withdrawal",
    accountType: "savings",
    amount: 2000,
    status: "pending_approval",
    createdAt: "2026-03-27T07:40:00Z",
  },
];

export const activeLoan: LoanDetailSummary = {
  id: "ln-0012",
  memberId: "mbr-00124",
  memberName: "John Nkem",
  branchId: "br-bamenda",
  approvedPrincipal: 100000,
  remainingPrincipal: 80000,
  monthlyInterestRate: 0.05,
  status: "active",
  nextInterestDue: 4000,
  collateralRequired: true,
};
